services:
  linkstack:
    image: ilyavassyutovich/linkstack:v4.8.4
    container_name: linkstack
    hostname: linkstack
    restart: unless-stopped
    ports:
      - "8878:80"
    environment:
      TZ: "Europe/Zurich"
      PHP_MEMORY_LIMIT: "512M"
      UPLOAD_MAX_FILESIZE: "16M"
      HTTPS_SERVER_NAME: "the-food-revolution.com"    # Optional
      LOG_LEVEL: "info"
      FORCE_HTTPS: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8878"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
