services:
  linkstack:
    image: linkstackorg/linkstack:latest
    environment:
      - TZ=Europe/Berlin
      - SERVER_ADMIN=gabrielle.coulon@yahoo.fr
      - HTTP_SERVER_NAME=localhost
      - HTTPS_SERVER_NAME=links.the-food-revolution.com
      - LOG_LEVEL=info
      - PHP_MEMORY_LIMIT=512M
      - UPLOAD_MAX_FILESIZE=16M
    ports:
      - "8879:80"
    volumes:
      #- linkstack:/htdocs
      - $LINKSTACK_BASE_PATH/htdocs:/htdocs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - hephaistos

networks:
  hephaistos:
    external: true

#volumes:
#  linkstack:
