services:
  ghost-the-food-revolution:
    image: ghost:5
    container_name: ghost_the_food_revolution
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db-the-food-revolution
      database__connection__user: ghost_the_food_revolution
      database__connection__password: ghostpass
      database__connection__database: ghostdb_the_food_revolution
      url: "https://the-food-revolution.com"
      TRUST_PROXY: true
      force__https: false
      security__staffDeviceVerification: false
    volumes:
      - $GHOST_BASE_PATH/the-food-revolution/content:/var/lib/ghost/content
      - $GHOST_BASE_PATH/the-food-revolution/config.production.json:/var/lib/ghost/config.production.json
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db-the-food-revolution
    networks:
        - hephaistos

  db-the-food-revolution:
    image: mysql:8
    container_name: ghost_db_the_food_revolution
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb_the_food_revolution
      MYSQL_USER: ghost_the_food_revolution
      MYSQL_PASSWORD: ghostpass
    volumes:
      - $GHOST_BASE_PATH/mysql-the-food-revolution:/var/lib/mysql
    networks:
      - hephaistos

networks:
  hephaistos:
    external: true
