services:
  ghost-petits-bouts:
    image: ghost:5
    container_name: ghost_petits_bouts
    restart: always
    environment:
      database__client: mysql
      database__connection__host: db-petits-bouts
      database__connection__user: ghost_petits_bouts
      database__connection__password: ghostpass
      database__connection__database: ghostdb_petits_bouts
      # url: "https://petits-bouts.com"
      # NODE_ENV: development
      TRUST_PROXY: true
      security__staffDeviceVerification: false
    volumes:
      - $GHOST_BASE_PATH/petits-bouts/content:/var/lib/ghost/content
      - $GHOST_BASE_PATH/petits-bouts/config.production.json:/var/lib/ghost/config.production.json
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db-petits-bouts
    networks:
        - hephaistos

  db-petits-bouts:
    image: mysql:8
    container_name: ghost_db_petits_bouts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ghostdb_petits_bouts
      MYSQL_USER: ghost_petits_bouts
      MYSQL_PASSWORD: ghostpass
    volumes:
      - $GHOST_BASE_PATH/mysql-petits-bouts:/var/lib/mysql
    networks:
      - hephaistos

networks:
  hephaistos:
    external: true
